/**
 * Combat constants — all values driving combat calculations.
 */
export const COMBAT_CONSTANTS = {
  BASE_HP: 100,
  BASE_QI: 50,
  HP_PER_REALM: 50,
  QI_PER_REALM: 25,
  BASE_ATTACK: 10,
  BASE_DEFENSE: 5,
  BASE_SPEED: 10,
  BASE_CRIT_RATE: 0.05,
  CRIT_MULTIPLIER: 1.5,
  INJURY_HP_PENALTY: 0.10,
  INJURY_DURATION_DAYS: 3,
  DEATH_CULTIVATION_PENALTY: 0.10,
  REVIVAL_COST_ST: 50,
  DAMAGE_VARIANCE: 0.1,
  DAMAGE_FLOOR_TURNS: 3,
  BASE_DODGE_CHANCE: 0.05,
  BLOCK_DAMAGE_REDUCTION: 0.5,
  BLOCK_COOLDOWN_TURNS: 3,
} as const;

export const INJURY_LEVELS = {
  NONE: 0,
  MINOR: 1,
  MODERATE: 2,
  SEVERE: 3,
  CRITICAL: 4,
} as const;
